export default {
  SET_APPLICATIONS: 'SET_APPLICATIONS',
  SET_NAME: 'SET_NAME',
  SET_RATING: 'SET_RATING',
  SET_PLATFORM: 'SET_PLATFORM',
  ADD_MODULE: 'ADD_MODULE',
  ADD_MODULE_NAME: 'ADD_MODULE_NAME',
  CHANGE_CURRENT_DESKTOP: 'CHANGE_CURRENT_DESKTOP',
  SET_ID_NAME: 'SET_ID_NAME',
}